kind = "web"
previewPath = "/"
title = "পাইকারি69bd.com"
version = "1.0.0"
id = "artifacts/paikari"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23592

[services.development]
run = "pnpm --filter @workspace/paikari run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/paikari", "run", "build" ]
publicDir = "artifacts/paikari/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23592"
BASE_PATH = "/"
