import {
  getDb,
  saveDb,
  setDb,
  DEFAULT_SETTINGS,
  type Product,
  type Category,
  type Review,
} from "./store";

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

const CATEGORIES: Category[] = [
  { slug: "fashion", nameBn: "ফ্যাশন ও পোশাক", nameEn: "Fashion & Apparel", icon: "Shirt", productCount: 0 },
  { slug: "electronics", nameBn: "ইলেকট্রনিক্স", nameEn: "Electronics", icon: "Smartphone", productCount: 0 },
  { slug: "grocery", nameBn: "মুদি ও খাবার", nameEn: "Grocery & Food", icon: "ShoppingBasket", productCount: 0 },
  { slug: "home", nameBn: "হোম ও কিচেন", nameEn: "Home & Kitchen", icon: "Home", productCount: 0 },
  { slug: "beauty", nameBn: "বিউটি ও কেয়ার", nameEn: "Beauty & Care", icon: "Sparkles", productCount: 0 },
  { slug: "kids", nameBn: "বাচ্চাদের পণ্য", nameEn: "Kids & Toys", icon: "Baby", productCount: 0 },
  { slug: "stationery", nameBn: "স্টেশনারি", nameEn: "Stationery", icon: "Pencil", productCount: 0 },
  { slug: "accessories", nameBn: "এক্সেসরিজ", nameEn: "Accessories", icon: "Watch", productCount: 0 },
];

const IMG = (q: string) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=900&q=70`;

type Seed = Omit<Product, "id" | "slug" | "categoryNameBn" | "gallery"> & {
  gallery?: string[];
};

const DAY = 24 * 60 * 60 * 1000;
const flashEndsAt = new Date(Date.now() + 2 * DAY).toISOString();

const SEED: Seed[] = [
  {
    titleBn: "প্রিমিয়াম কটন পাঞ্জাবি (পুরুষ)",
    titleEn: "Premium Cotton Panjabi",
    descriptionBn: "১০০% কটন কাপড়, রিসেলারদের জন্য বিশেষ পাইকারি দাম। সাইজ M, L, XL, XXL মিক্স প্যাক।",
    category: "fashion",
    source: "কেরানীগঞ্জ, ঢাকা",
    image: "photo-1602810318383-e386cc2a3ccf",
    oldPrice: 950,
    wholesalePrice: 520,
    moq: 6,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 750, label: "১ পিস (খুচরা)" },
      { minQty: 6, price: 520, label: "৬+ পিস" },
      { minQty: 24, price: 470, label: "২৪+ পিস (কার্টন)" },
    ],
    stock: 320,
    badges: ["ফ্ল্যাশ ডিল", "বেস্টসেলার"],
    rating: 4.7,
    sold: 1840,
    deliveryNote: "ঢাকার ভিতরে ১-২ দিন, ঢাকার বাইরে ২-৪ দিন",
    flashEndsAt,
    tags: ["flash", "bestseller"],
  },
  {
    titleBn: "থ্রি-পিস উইন্টার কালেকশন",
    titleEn: "Three Piece Winter Collection",
    descriptionBn: "জর্জেট কাপড়, এমব্রয়ডারি ডিজাইন। মিক্স কালার প্যাক।",
    category: "fashion",
    source: "ইসলামপুর, ঢাকা",
    image: "photo-1583391733956-6c78276477e2",
    oldPrice: 1850,
    wholesalePrice: 980,
    moq: 4,
    unit: "সেট",
    tiers: [
      { minQty: 1, price: 1200, label: "১ সেট" },
      { minQty: 4, price: 980, label: "৪+ সেট" },
      { minQty: 12, price: 880, label: "১২+ সেট" },
    ],
    stock: 145,
    badges: ["নতুন"],
    rating: 4.6,
    sold: 720,
    deliveryNote: "সারাদেশে কুরিয়ারে ডেলিভারি",
    tags: ["new", "featured"],
  },
  {
    titleBn: "স্মার্টওয়াচ Y68 (মিক্স কালার)",
    titleEn: "Smartwatch Y68",
    descriptionBn: "ব্লুটুথ কল, হার্ট-রেট, স্টেপ কাউন্টার। রিসেলারদের জন্য পাইকারি প্যাক।",
    category: "electronics",
    source: "ইম্পোর্টেড, চট্টগ্রাম পোর্ট",
    image: "photo-1546868871-7041f2a55e12",
    oldPrice: 850,
    wholesalePrice: 320,
    moq: 10,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 450, label: "১ পিস" },
      { minQty: 10, price: 320, label: "১০+ পিস" },
      { minQty: 50, price: 285, label: "৫০+ পিস" },
    ],
    stock: 540,
    badges: ["ফ্ল্যাশ ডিল", "হট"],
    rating: 4.4,
    sold: 3210,
    deliveryNote: "১-৩ দিনে সারাদেশে",
    flashEndsAt,
    tags: ["flash", "bestseller"],
  },
  {
    titleBn: "ব্লুটুথ ইয়ারবাড TWS Pro",
    titleEn: "TWS Pro Earbuds",
    descriptionBn: "এনসি সাপোর্টেড, ৪+২০ ঘন্টা ব্যাকআপ। ভালো বিল্ড কোয়ালিটি।",
    category: "electronics",
    source: "ইম্পোর্টেড, চট্টগ্রাম",
    image: "photo-1606220588913-b3aacb4d2f46",
    oldPrice: 1200,
    wholesalePrice: 480,
    moq: 10,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 650, label: "১ পিস" },
      { minQty: 10, price: 480, label: "১০+ পিস" },
      { minQty: 30, price: 430, label: "৩০+ পিস" },
    ],
    stock: 280,
    badges: ["বেস্টসেলার"],
    rating: 4.5,
    sold: 2450,
    deliveryNote: "১-৩ দিনে সারাদেশে",
    tags: ["bestseller"],
  },
  {
    titleBn: "প্রিমিয়াম বাসমতি চাল ৫ কেজি",
    titleEn: "Premium Basmati Rice 5kg",
    descriptionBn: "এক্সপোর্ট কোয়ালিটি, ১২ মাস স্টোরেজ। মুদি দোকানদারদের জন্য পাইকারি।",
    category: "grocery",
    source: "নাটোর",
    image: "photo-1586201375761-83865001e31c",
    oldPrice: 720,
    wholesalePrice: 540,
    moq: 5,
    unit: "ব্যাগ",
    tiers: [
      { minQty: 1, price: 620, label: "১ ব্যাগ" },
      { minQty: 5, price: 540, label: "৫+ ব্যাগ" },
      { minQty: 20, price: 510, label: "২০+ ব্যাগ (বস্তা)" },
    ],
    stock: 800,
    badges: ["ফ্রেশ স্টক"],
    rating: 4.8,
    sold: 5400,
    deliveryNote: "ঢাকা ও আশেপাশে দ্রুত ডেলিভারি",
    tags: ["bestseller"],
  },
  {
    titleBn: "সয়াবিন তেল ৫ লিটার (পেট বোতল)",
    titleEn: "Soybean Oil 5L",
    descriptionBn: "রিফাইন্ড সয়াবিন তেল, ব্র্যান্ডেড সিল প্যাক।",
    category: "grocery",
    source: "ময়মনসিংহ ডিপো",
    image: "photo-1474979266404-7eaacbcd87c5",
    oldPrice: 950,
    wholesalePrice: 820,
    moq: 6,
    unit: "বোতল",
    tiers: [
      { minQty: 1, price: 880, label: "১ বোতল" },
      { minQty: 6, price: 820, label: "৬+ বোতল" },
      { minQty: 24, price: 790, label: "২৪+ বোতল" },
    ],
    stock: 220,
    badges: [],
    rating: 4.5,
    sold: 1900,
    deliveryNote: "ঢাকার ভিতরে ১ দিনে",
  },
  {
    titleBn: "স্টেইনলেস স্টিল কুকওয়্যার সেট (৭ পিস)",
    titleEn: "Steel Cookware Set 7pc",
    descriptionBn: "টেকসই বিল্ড, ইন্ডাকশন কম্প্যাটিবল।",
    category: "home",
    source: "নারায়ণগঞ্জ",
    image: "photo-1584990347449-a08a6d8d0d7e",
    oldPrice: 3200,
    wholesalePrice: 1980,
    moq: 3,
    unit: "সেট",
    tiers: [
      { minQty: 1, price: 2400, label: "১ সেট" },
      { minQty: 3, price: 1980, label: "৩+ সেট" },
      { minQty: 10, price: 1850, label: "১০+ সেট" },
    ],
    stock: 88,
    badges: ["নতুন"],
    rating: 4.6,
    sold: 410,
    deliveryNote: "৩-৫ দিনে সারাদেশে",
    tags: ["new"],
  },
  {
    titleBn: "নন-স্টিক ফ্রাই প্যান ২৬cm",
    titleEn: "Non-stick Fry Pan",
    descriptionBn: "৫ লেয়ার নন-স্টিক কোটিং।",
    category: "home",
    source: "চট্টগ্রাম",
    image: "photo-1556910103-1c02745aae4d",
    oldPrice: 950,
    wholesalePrice: 540,
    moq: 6,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 720, label: "১ পিস" },
      { minQty: 6, price: 540, label: "৬+ পিস" },
      { minQty: 24, price: 495, label: "২৪+ পিস" },
    ],
    stock: 175,
    badges: [],
    rating: 4.4,
    sold: 980,
    deliveryNote: "৩-৫ দিনে",
  },
  {
    titleBn: "হারবাল ফেস ওয়াশ ১০০ml",
    titleEn: "Herbal Face Wash",
    descriptionBn: "নিম ও তুলসী ব্লেন্ড, সব স্কিন টাইপের জন্য।",
    category: "beauty",
    source: "লোকাল ব্র্যান্ড, ঢাকা",
    image: "photo-1556228720-195a672e8a03",
    oldPrice: 220,
    wholesalePrice: 95,
    moq: 24,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 150, label: "১ পিস" },
      { minQty: 24, price: 95, label: "২৪+ পিস (কার্টন)" },
      { minQty: 144, price: 85, label: "১৪৪+ পিস (১২ কার্টন)" },
    ],
    stock: 1200,
    badges: ["বেস্টসেলার"],
    rating: 4.7,
    sold: 8900,
    deliveryNote: "১-৩ দিনে সারাদেশে",
    tags: ["bestseller"],
  },
  {
    titleBn: "লিপস্টিক সেট (৬ কালার)",
    titleEn: "Lipstick Set",
    descriptionBn: "ম্যাট ফিনিশ, লং লাস্টিং।",
    category: "beauty",
    source: "ইম্পোর্টেড",
    image: "photo-1586495777744-4413f21062fa",
    oldPrice: 850,
    wholesalePrice: 380,
    moq: 6,
    unit: "সেট",
    tiers: [
      { minQty: 1, price: 520, label: "১ সেট" },
      { minQty: 6, price: 380, label: "৬+ সেট" },
      { minQty: 24, price: 340, label: "২৪+ সেট" },
    ],
    stock: 95,
    badges: ["ফ্ল্যাশ ডিল"],
    rating: 4.5,
    sold: 670,
    deliveryNote: "১-৩ দিনে",
    flashEndsAt,
    tags: ["flash"],
  },
  {
    titleBn: "বাচ্চাদের ফ্যামিলি প্যাক ডায়াপার",
    titleEn: "Baby Diaper Family Pack",
    descriptionBn: "M/L/XL সাইজ মিক্স, ৪৮ পিস।",
    category: "kids",
    source: "ইম্পোর্টেড",
    image: "photo-1515488042361-ee00e0ddd4e4",
    oldPrice: 1450,
    wholesalePrice: 980,
    moq: 4,
    unit: "প্যাক",
    tiers: [
      { minQty: 1, price: 1180, label: "১ প্যাক" },
      { minQty: 4, price: 980, label: "৪+ প্যাক" },
      { minQty: 12, price: 920, label: "১২+ প্যাক" },
    ],
    stock: 210,
    badges: ["বেস্টসেলার"],
    rating: 4.7,
    sold: 1320,
    deliveryNote: "১-৩ দিনে",
    tags: ["bestseller"],
  },
  {
    titleBn: "কাঠের শিক্ষামূলক খেলনা সেট",
    titleEn: "Wooden Educational Toys",
    descriptionBn: "নন-টক্সিক পেইন্ট, ৩+ বছর বয়সী বাচ্চাদের জন্য।",
    category: "kids",
    source: "লোকাল হ্যান্ডমেইড",
    image: "photo-1558877385-81a1c7e67d72",
    oldPrice: 750,
    wholesalePrice: 420,
    moq: 6,
    unit: "সেট",
    tiers: [
      { minQty: 1, price: 580, label: "১ সেট" },
      { minQty: 6, price: 420, label: "৬+ সেট" },
      { minQty: 20, price: 380, label: "২০+ সেট" },
    ],
    stock: 130,
    badges: ["নতুন"],
    rating: 4.6,
    sold: 245,
    deliveryNote: "৩-৫ দিনে",
    tags: ["new"],
  },
  {
    titleBn: "প্রিমিয়াম এ৪ পেপার রিম (৫০০ পিস)",
    titleEn: "A4 Paper Ream 500pc",
    descriptionBn: "৭৫ জিএসএম, অফিস ও স্কুল ইউজের জন্য।",
    category: "stationery",
    source: "লোকাল মিল",
    image: "photo-1583521214690-73421a1829a9",
    oldPrice: 480,
    wholesalePrice: 360,
    moq: 10,
    unit: "রিম",
    tiers: [
      { minQty: 1, price: 420, label: "১ রিম" },
      { minQty: 10, price: 360, label: "১০+ রিম" },
      { minQty: 50, price: 340, label: "৫০+ রিম" },
    ],
    stock: 600,
    badges: [],
    rating: 4.6,
    sold: 2100,
    deliveryNote: "১-৩ দিনে",
  },
  {
    titleBn: "প্রিমিয়াম জেল কলম (৫০ পিস বক্স)",
    titleEn: "Gel Pen Box",
    descriptionBn: "স্মুথ রাইটিং, ০.৫mm টিপ।",
    category: "stationery",
    source: "ইম্পোর্টেড",
    image: "photo-1517242810446-cc8951b2be40",
    oldPrice: 350,
    wholesalePrice: 195,
    moq: 12,
    unit: "বক্স",
    tiers: [
      { minQty: 1, price: 250, label: "১ বক্স" },
      { minQty: 12, price: 195, label: "১২+ বক্স" },
      { minQty: 60, price: 175, label: "৬০+ বক্স" },
    ],
    stock: 410,
    badges: ["বেস্টসেলার"],
    rating: 4.5,
    sold: 3400,
    deliveryNote: "১-৩ দিনে",
    tags: ["bestseller"],
  },
  {
    titleBn: "ছেলেদের লেদার বেল্ট (মিক্স)",
    titleEn: "Men Leather Belt",
    descriptionBn: "জেনুইন PU লেদার, অটো-লক বাকল।",
    category: "accessories",
    source: "ইসলামপুর, ঢাকা",
    image: "photo-1624222247344-550fb60583a8",
    oldPrice: 650,
    wholesalePrice: 280,
    moq: 12,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 380, label: "১ পিস" },
      { minQty: 12, price: 280, label: "১২+ পিস" },
      { minQty: 48, price: 250, label: "৪৮+ পিস" },
    ],
    stock: 320,
    badges: ["ফ্ল্যাশ ডিল"],
    rating: 4.4,
    sold: 1450,
    deliveryNote: "১-৩ দিনে",
    flashEndsAt,
    tags: ["flash", "bestseller"],
  },
  {
    titleBn: "মেয়েদের হিজাব পিন সেট (২৪ পিস)",
    titleEn: "Hijab Pin Set",
    descriptionBn: "মিক্স ডিজাইন, প্রিমিয়াম স্টোন ফিনিশ।",
    category: "accessories",
    source: "লোকাল",
    image: "photo-1611591437281-460bfbe1220a",
    oldPrice: 420,
    wholesalePrice: 175,
    moq: 12,
    unit: "সেট",
    tiers: [
      { minQty: 1, price: 240, label: "১ সেট" },
      { minQty: 12, price: 175, label: "১২+ সেট" },
      { minQty: 60, price: 155, label: "৬০+ সেট" },
    ],
    stock: 540,
    badges: ["নতুন"],
    rating: 4.6,
    sold: 880,
    deliveryNote: "১-৩ দিনে",
    tags: ["new"],
  },
  // ─── FEATURED: JERSEYS ───────────────────────────────────────────────
  {
    titleBn: "ওয়ার্ল্ড কাপ ২০২৬ অফিসিয়াল জার্সি (প্রিমিয়াম এডিশন)",
    titleEn: "World Cup 2026 Official Jersey Premium",
    descriptionBn:
      "FIFA ওয়ার্ল্ড কাপ ২০২৬ স্পেশাল এডিশন জার্সি — প্রিমিয়াম ড্রাই-ফিট পলিয়েস্টার, AAA+ কোয়ালিটি, স্বাস ক্ষমতা সম্পন্ন কাপড়। সাইজ M, L, XL, XXL মিক্স প্যাক। সব দল অ্যাভেইলেবল — আর্জেন্টিনা, ব্রাজিল, পর্তুগাল, ফ্রান্স, স্পেন, জার্মানি। সীমিত স্টক, সীমিত সময়ের অফার!",
    category: "fashion",
    source: "ইসলামপুর, ঢাকা — ডাইরেক্ট ইম্পোর্ট",
    image: "photo-1577223625816-7546f13df25d",
    oldPrice: 1450,
    wholesalePrice: 580,
    moq: 5,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 750, label: "১ পিস (খুচরা)" },
      { minQty: 5, price: 580, label: "৫+ পিস (পাইকারি)" },
      { minQty: 10, price: 490, label: "১০+ পিস (বেস্ট ডিল)" },
    ],
    stock: 45,
    badges: ["হট", "নতুন", "বেস্টসেলার"],
    rating: 4.9,
    sold: 5240,
    deliveryNote: "সারাদেশে ১-৩ দিন • ঢাকার ভিতরে সেইম ডে ডেলিভারি",
    flashEndsAt,
    tags: ["bestseller", "flash", "new", "featured-jersey"],
  },
  {
    titleBn: "আর্জেন্টিনা হোম জার্সি ২০২৬ (ফ্যান এডিশন)",
    titleEn: "Argentina Home Jersey 2026 Fan",
    descriptionBn: "ড্রাই-ফিট পলিয়েস্টার, স্বাস ক্ষমতা সম্পন্ন কাপড়। সাইজ M, L, XL, XXL মিক্স প্যাক। AAA কোয়ালিটি।",
    category: "fashion",
    source: "ইসলামপুর, ঢাকা",
    image: "photo-1556906781-9a412961c28c",
    oldPrice: 950,
    wholesalePrice: 420,
    moq: 5,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 550, label: "১ পিস" },
      { minQty: 5, price: 420, label: "৫+ পিস" },
      { minQty: 10, price: 360, label: "১০+ পিস" },
    ],
    stock: 540,
    badges: ["হট", "বেস্টসেলার"],
    rating: 4.8,
    sold: 3120,
    deliveryNote: "সারাদেশে ১-৩ দিন",
    flashEndsAt,
    tags: ["bestseller", "featured-jersey"],
  },
  {
    titleBn: "ব্রাজিল হোম জার্সি ২০২৬ (প্লেয়ার এডিশন)",
    titleEn: "Brazil Home Jersey 2026 Player",
    descriptionBn: "প্রিমিয়াম স্পোর্ট কাপড়, পেশাদার ফিনিশিং। নাম-নাম্বার প্রিন্ট অপশন আছে।",
    category: "fashion",
    source: "ইসলামপুর, ঢাকা",
    image: "photo-1517466787929-bc90951d0974",
    oldPrice: 1100,
    wholesalePrice: 480,
    moq: 5,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 620, label: "১ পিস" },
      { minQty: 5, price: 480, label: "৫+ পিস" },
      { minQty: 10, price: 410, label: "১০+ পিস" },
    ],
    stock: 410,
    badges: ["হট"],
    rating: 4.7,
    sold: 2240,
    deliveryNote: "সারাদেশে ১-৩ দিন",
    tags: ["featured-jersey"],
  },
  {
    titleBn: "বাংলাদেশ ক্রিকেট জার্সি ২০২৬",
    titleEn: "Bangladesh Cricket Jersey 2026",
    descriptionBn: "অরিজিনাল ফ্যান এডিশন, BCB স্টাইল। মিক্স সাইজ প্যাক।",
    category: "fashion",
    source: "ইসলামপুর, ঢাকা",
    image: "photo-1551958219-acbc608c6377",
    oldPrice: 890,
    wholesalePrice: 390,
    moq: 5,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 520, label: "১ পিস" },
      { minQty: 5, price: 390, label: "৫+ পিস" },
      { minQty: 10, price: 330, label: "১০+ পিস" },
    ],
    stock: 620,
    badges: ["বেস্টসেলার"],
    rating: 4.9,
    sold: 4180,
    deliveryNote: "সারাদেশে ১-৩ দিন",
    tags: ["bestseller", "featured-jersey"],
  },
  {
    titleBn: "পর্তুগাল অ্যাওয়ে জার্সি ২০২৬",
    titleEn: "Portugal Away Jersey 2026",
    descriptionBn: "সাদা-মেরুন প্রিমিয়াম এডিশন। লাইট-ওয়েট, কুইক ড্রাই।",
    category: "fashion",
    source: "ইসলামপুর, ঢাকা",
    image: "photo-1521572163474-6864f9cf17ab",
    oldPrice: 1050,
    wholesalePrice: 450,
    moq: 5,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 590, label: "১ পিস" },
      { minQty: 5, price: 450, label: "৫+ পিস" },
      { minQty: 10, price: 385, label: "১০+ পিস" },
    ],
    stock: 380,
    badges: ["নতুন"],
    rating: 4.6,
    sold: 1380,
    deliveryNote: "সারাদেশে ১-৩ দিন",
    tags: ["featured-jersey"],
  },
  // ─── FEATURED: TANGAIL SAREES ────────────────────────────────────────
  {
    titleBn: "টাঙ্গাইল হাফ সিল্ক শাড়ি (অরিজিনাল)",
    titleEn: "Tangail Half Silk Saree Original",
    descriptionBn: "টাঙ্গাইলের তাঁতিদের হাতে বোনা, ১০০% অথেনটিক হাফ সিল্ক। ব্লাউজ পিস সহ। মিক্স কালার ৬টি ডিজাইন।",
    category: "fashion",
    source: "টাঙ্গাইল",
    image: "photo-1610030469983-98e550d6193c",
    oldPrice: 2400,
    wholesalePrice: 1180,
    moq: 5,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 1450, label: "১ পিস" },
      { minQty: 5, price: 1180, label: "৫+ পিস" },
      { minQty: 10, price: 1050, label: "১০+ পিস" },
    ],
    stock: 220,
    badges: ["হট", "বেস্টসেলার"],
    rating: 4.9,
    sold: 1640,
    deliveryNote: "সারাদেশে কুরিয়ারে ২-৪ দিন",
    flashEndsAt,
    tags: ["bestseller", "featured-saree"],
  },
  {
    titleBn: "টাঙ্গাইল জামদানি শাড়ি (প্রিমিয়াম)",
    titleEn: "Tangail Jamdani Saree Premium",
    descriptionBn: "ঐতিহ্যবাহী জামদানি বুনন, রিচ আঁচল ডিজাইন। হাত বুননের পিউর কাপড়।",
    category: "fashion",
    source: "টাঙ্গাইল",
    image: "photo-1583391733981-3eef1d12d889",
    oldPrice: 3200,
    wholesalePrice: 1650,
    moq: 5,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 1990, label: "১ পিস" },
      { minQty: 5, price: 1650, label: "৫+ পিস" },
      { minQty: 10, price: 1450, label: "১০+ পিস" },
    ],
    stock: 145,
    badges: ["হট"],
    rating: 4.8,
    sold: 920,
    deliveryNote: "সারাদেশে কুরিয়ারে ২-৪ দিন",
    tags: ["featured-saree"],
  },
  {
    titleBn: "টাঙ্গাইল কটন তাঁত শাড়ি (ডেইলি)",
    titleEn: "Tangail Cotton Tant Saree Daily",
    descriptionBn: "১০০% কটন, আরামদায়ক ডেইলি ওয়্যার। হালকা ও নরম। মিক্স ১২ কালার।",
    category: "fashion",
    source: "টাঙ্গাইল",
    image: "photo-1594387303048-3aa31b3f88f5",
    oldPrice: 1450,
    wholesalePrice: 720,
    moq: 5,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 890, label: "১ পিস" },
      { minQty: 5, price: 720, label: "৫+ পিস" },
      { minQty: 10, price: 640, label: "১০+ পিস" },
    ],
    stock: 480,
    badges: ["বেস্টসেলার"],
    rating: 4.7,
    sold: 2840,
    deliveryNote: "সারাদেশে কুরিয়ারে ২-৪ দিন",
    tags: ["bestseller", "featured-saree"],
  },
  {
    titleBn: "টাঙ্গাইল সফট সিল্ক বেনারসি লুক",
    titleEn: "Tangail Soft Silk Benarasi Look",
    descriptionBn: "বেনারসি স্টাইলের রিচ ডিজাইন, বিয়ে ও পার্টি ওয়্যার।",
    category: "fashion",
    source: "টাঙ্গাইল",
    image: "photo-1610030469983-98e550d6193c",
    oldPrice: 2850,
    wholesalePrice: 1380,
    moq: 5,
    unit: "পিস",
    tiers: [
      { minQty: 1, price: 1720, label: "১ পিস" },
      { minQty: 5, price: 1380, label: "৫+ পিস" },
      { minQty: 10, price: 1210, label: "১০+ পিস" },
    ],
    stock: 180,
    badges: ["নতুন"],
    rating: 4.7,
    sold: 760,
    deliveryNote: "সারাদেশে কুরিয়ারে ২-৪ দিন",
    tags: ["featured-saree"],
  },
  // ─── FEATURED: THREE-PIECE ───────────────────────────────────────────
  {
    titleBn: "প্রিমিয়াম জর্জেট থ্রি-পিস (এমব্রয়ডারি)",
    titleEn: "Premium Georgette Three Piece Embroidery",
    descriptionBn: "ভারি এমব্রয়ডারি কাজ, স্টোন ওয়ার্ক। দোপাট্টা ও সালোয়ার সহ ফুল সেট।",
    category: "fashion",
    source: "ইসলামপুর, ঢাকা",
    image: "photo-1610030469983-98e550d6193c",
    oldPrice: 2200,
    wholesalePrice: 1050,
    moq: 5,
    unit: "সেট",
    tiers: [
      { minQty: 1, price: 1320, label: "১ সেট" },
      { minQty: 5, price: 1050, label: "৫+ সেট" },
      { minQty: 10, price: 920, label: "১০+ সেট" },
    ],
    stock: 280,
    badges: ["হট", "বেস্টসেলার"],
    rating: 4.8,
    sold: 1980,
    deliveryNote: "সারাদেশে ১-৩ দিন",
    flashEndsAt,
    tags: ["bestseller", "featured-threepiece"],
  },
  {
    titleBn: "লন কটন থ্রি-পিস কালেকশন (গ্রীষ্মকাল)",
    titleEn: "Lawn Cotton Three Piece Summer",
    descriptionBn: "পাকিস্তানি লন প্রিন্ট, হালকা কাপড়, গরমে আরামদায়ক। মিক্স ৮টি ডিজাইন।",
    category: "fashion",
    source: "ইসলামপুর, ঢাকা",
    image: "photo-1583391733956-6c78276477e2",
    oldPrice: 1850,
    wholesalePrice: 880,
    moq: 5,
    unit: "সেট",
    tiers: [
      { minQty: 1, price: 1100, label: "১ সেট" },
      { minQty: 5, price: 880, label: "৫+ সেট" },
      { minQty: 10, price: 770, label: "১০+ সেট" },
    ],
    stock: 360,
    badges: ["বেস্টসেলার"],
    rating: 4.7,
    sold: 2410,
    deliveryNote: "সারাদেশে ১-৩ দিন",
    tags: ["bestseller", "featured-threepiece"],
  },
  {
    titleBn: "ইন্ডিয়ান আনস্টিচড থ্রি-পিস (পার্টি)",
    titleEn: "Indian Unstitched Three Piece Party",
    descriptionBn: "ভারি পার্টি ওয়্যার, রিচ ফেব্রিক ও ডিজাইন। বিয়ে ও অনুষ্ঠানের জন্য।",
    category: "fashion",
    source: "ইসলামপুর, ঢাকা",
    image: "photo-1594387303048-3aa31b3f88f5",
    oldPrice: 2650,
    wholesalePrice: 1280,
    moq: 5,
    unit: "সেট",
    tiers: [
      { minQty: 1, price: 1620, label: "১ সেট" },
      { minQty: 5, price: 1280, label: "৫+ সেট" },
      { minQty: 10, price: 1120, label: "১০+ সেট" },
    ],
    stock: 200,
    badges: ["হট", "নতুন"],
    rating: 4.8,
    sold: 1140,
    deliveryNote: "সারাদেশে ১-৩ দিন",
    tags: ["featured-threepiece"],
  },
  {
    titleBn: "প্রিন্ট সুতি থ্রি-পিস (ক্যাজুয়াল)",
    titleEn: "Printed Cotton Three Piece Casual",
    descriptionBn: "১০০% কটন, ডেইলি ওয়্যার। মিক্স কালার ১০টি ডিজাইন।",
    category: "fashion",
    source: "নারায়ণগঞ্জ",
    image: "photo-1583391733956-6c78276477e2",
    oldPrice: 1350,
    wholesalePrice: 650,
    moq: 5,
    unit: "সেট",
    tiers: [
      { minQty: 1, price: 820, label: "১ সেট" },
      { minQty: 5, price: 650, label: "৫+ সেট" },
      { minQty: 10, price: 570, label: "১০+ সেট" },
    ],
    stock: 540,
    badges: ["বেস্টসেলার"],
    rating: 4.6,
    sold: 3210,
    deliveryNote: "সারাদেশে ১-৩ দিন",
    tags: ["bestseller", "featured-threepiece"],
  },
];

function uid(): string {
  return Math.random().toString(36).slice(2, 10);
}

function buildProduct(s: Seed): Product {
  const slug = `${slugify(s.titleEn)}-${uid().slice(0, 4)}`;
  const cat = CATEGORIES.find((c) => c.slug === s.category);
  return {
    id: uid(),
    slug,
    categoryNameBn: cat?.nameBn,
    gallery: s.gallery ?? [IMG(s.image), IMG(s.image), IMG(s.image)],
    ...s,
    image: IMG(s.image),
  };
}

export function ensureSeed(): void {
  const db = getDb();
  if (db.products.length > 0) {
    // Append any new featured products that don't yet exist (by titleEn).
    const existingTitles = new Set(db.products.map((p) => p.titleEn));
    const featuredTags = new Set(["featured-jersey", "featured-saree", "featured-threepiece"]);
    const missing = SEED.filter(
      (s) => !existingTitles.has(s.titleEn) && (s.tags ?? []).some((t) => featuredTags.has(t)),
    );
    if (missing.length > 0) {
      db.products.push(...missing.map(buildProduct));
    }
    const map = new Map(CATEGORIES.map((c) => [c.slug, { ...c, productCount: 0 }]));
    for (const p of db.products) {
      const c = map.get(p.category);
      if (c) c.productCount += 1;
    }
    (db as unknown as { categories?: Category[] }).categories = Array.from(map.values());
    if (!db.reviews || db.reviews.length === 0) {
      db.reviews = [
        {
          id: uid(),
          customerName: "মোঃ রফিকুল ইসলাম",
          customerPhone: "01711-234567",
          productTitleBn: "ওয়ার্ল্ড কাপ ২০২৬ অফিসিয়াল জার্সি",
          rating: 5,
          text: "অসাধারণ কোয়ালিটি! ১০ পিস নিয়েছিলাম, সবগুলোর কাপড় খুব ভালো।",
          status: "approved",
          featured: true,
          createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
        },
        {
          id: uid(),
          customerName: "শাহানা বেগম",
          customerPhone: "01812-345678",
          productTitleBn: "টাঙ্গাইল হাফ সিল্ক শাড়ি",
          rating: 5,
          text: "সরাসরি তাঁতি থেকে যেমন বললো, আসলেও সেরকমই। আমার সব কাস্টমার পছন্দ করেছে।",
          status: "approved",
          featured: true,
          createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
        },
        {
          id: uid(),
          customerName: "ফাহিম আহমেদ",
          rating: 4,
          text: "ডেলিভারি ২ দিনে পেয়েছি ঢাকার বাইরে। প্যাকিং খুব ভালো ছিল।",
          status: "pending",
          featured: false,
          createdAt: new Date(Date.now() - 86400000).toISOString(),
        },
      ];
    }
    if (!db.settings) db.settings = JSON.parse(JSON.stringify(DEFAULT_SETTINGS));
    if (!db.stockLogs) db.stockLogs = [];
    if (!db.smsLogs) db.smsLogs = [];
    if (!db.txnLogs) db.txnLogs = [];
    saveDb();
    return;
  }
  const products: Product[] = SEED.map((s) => {
    const slug = `${slugify(s.titleEn)}-${uid().slice(0, 4)}`;
    const cat = CATEGORIES.find((c) => c.slug === s.category);
    return {
      id: uid(),
      slug,
      categoryNameBn: cat?.nameBn,
      gallery: s.gallery ?? [
        IMG(s.image),
        IMG(s.image),
        IMG(s.image),
      ],
      ...s,
      image: IMG(s.image),
    };
  });
  const SAMPLE_REVIEWS: Review[] = [
    {
      id: uid(),
      customerName: "মোঃ রফিকুল ইসলাম",
      customerPhone: "01711-234567",
      productTitleBn: "ওয়ার্ল্ড কাপ ২০২৬ অফিসিয়াল জার্সি",
      rating: 5,
      text: "অসাধারণ কোয়ালিটি! ১০ পিস নিয়েছিলাম, সবগুলোর কাপড় খুব ভালো। দাম অনেক কম পেয়েছি অন্য জায়গার তুলনায়।",
      status: "approved",
      featured: true,
      createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
    {
      id: uid(),
      customerName: "শাহানা বেগম",
      customerPhone: "01812-345678",
      productTitleBn: "টাঙ্গাইল হাফ সিল্ক শাড়ি",
      rating: 5,
      text: "সরাসরি তাঁতি থেকে যেমন বললো, আসলেও সেরকমই। কালার একদম আসল। আমার দোকানের সব কাস্টমার পছন্দ করেছে।",
      status: "approved",
      featured: true,
      createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    },
    {
      id: uid(),
      customerName: "ফাহিম আহমেদ",
      customerPhone: "01900-456789",
      productTitleBn: "প্রিমিয়াম থ্রি-পিস",
      rating: 4,
      text: "ডেলিভারি ২ দিনে পেয়েছি ঢাকার বাইরে। প্যাকিং খুব ভালো ছিল। আবার অর্ডার করব।",
      status: "approved",
      featured: true,
      createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    },
    {
      id: uid(),
      customerName: "নাসরিন আক্তার",
      rating: 5,
      text: "৫ পিস টিয়ারে দাম খুবই সাশ্রয়ী। রিসেলার হিসেবে আমার লাভ হচ্ছে।",
      status: "pending",
      featured: false,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
    },
    {
      id: uid(),
      customerName: "Anonymous",
      rating: 1,
      text: "spam content xxxxxx",
      status: "pending",
      featured: false,
      createdAt: new Date(Date.now() - 3600000).toISOString(),
    },
  ];

  setDb({
    products,
    orders: [],
    users: [],
    otps: [],
    reviews: SAMPLE_REVIEWS,
    stockLogs: [],
    smsLogs: [],
    txnLogs: [],
    settings: JSON.parse(JSON.stringify(DEFAULT_SETTINGS)),
  });
}

export function getCategories(): Category[] {
  const counts = new Map<string, number>();
  for (const p of getDb().products) {
    counts.set(p.category, (counts.get(p.category) ?? 0) + 1);
  }
  return CATEGORIES.map((c) => ({
    ...c,
    productCount: counts.get(c.slug) ?? 0,
    image: IMG(
      {
        fashion: "photo-1483985988355-763728e1935b",
        electronics: "photo-1518770660439-4636190af475",
        grocery: "photo-1542838132-92c53300491e",
        home: "photo-1556909114-f6e7ad7d3136",
        beauty: "photo-1522335789203-aaa2bcdf6c9c",
        kids: "photo-1515488042361-ee00e0ddd4e4",
        stationery: "photo-1456735190827-d1262f71b8a3",
        accessories: "photo-1611591437281-460bfbe1220a",
      }[c.slug] ?? "photo-1483985988355-763728e1935b",
    ),
  }));
}

export function flashEndsAtIso(): string {
  return flashEndsAt;
}

ensureSeed();
